CREATE DATABASE STORE_INFO;
USE STORE_INFO;

CREATE TABLE STORE_SALES (MONTH VARCHAR (20) NOT NULL,
PROD_NAME VARCHAR (30) NOT NULL,
SALES INT);

INSERT INTO STORE_SALES (MONTH, PROD_NAME, SALES)
VALUES ("JANUARY","FRUITS", 45000),
("JANUARY","VEGETABLES",67000),
("JANUARY","DAIRY", 55000),
("FEBURARY","FRUITS",42000),
 ("FEBURARY","VEGETABLES",32000),
 ("FEBURARY","DAIRY",52000),
 ("MARCH","FRUITS",61000),
  ("MARCH","VEGETABLES",43000),
   ("MARCH","DAIRY",92000);
   
   SELECT* FROM STORE_SALES 






 